### ISSUE TITLE
Where is the Save file for the web demo?

### ISSUE THREAD

**Issue by swampthings** [pents90/eburp#6]
I'm wondering where the Save file gets put for the web demo.

But, maybe that's not the right question to ask. I want to be able to do testing on my version, and I'm hoping that I could just open the save file, make some modifications, and then I could do better testing, like modify the levels of my characters, to do tests against high level monsters, etc. So, I guess the right question is what do you think the best way of doing that testing is?

And, either way, I'm really curious where the save file goes. I can't find it.

**Comment by pents90** [comment]
On web and iOS It is saved into HTML5 local storage. On Android, it is saved to SharedPreferences. See device.coffee and index.html to see what is happening. To debug or play with it, you could either use some kind of local storage inspection/modification tool, or you could divert the saved games to some other kind of storage system.

**Comment by swampthings** [comment]
Okay, awesome. Thanks so much for walking me through this!
